spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: goods-route
          uri: lb://GOODS-PROVIDER8090
          predicates:
            - Path=/goods/**
        - id: order-route
          uri: lb://ORDER-CONSUMER8091
          predicates:
            - Path=/order/**
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: v4p6sWp5Mk7qR9tX2uN8yF3jH1kL5wB7cQ9zE4rT6yU=
  access-expiration: 1800000